name: UpgradeableChests
main: xyz.oribuin.upgradeablechests.UpgradeableChests
version: '1.0'
author: Oribuin
api-version: "1.16"
description: Store thousands of items in a single upgradeable chest
website: https://oribuin.xyz/
softdepend:
  - PlaceholderAPI